library(alarmdata)
library(redist)
library(ggplot2)
library(plotly)
library(ggredist)
library(dplyr)
library(redistmetrics)
library(sf)
library(PL94171)
library(tinytiger)
library(tidyr)
library(dplyr)
library(alarmdata)
library(readr)
map_fl <- alarm_50state_map('FL')
