library(alarmdata)
library(redist)
library(ggplot2)
library(plotly)
library(ggredist)
library(dplyr)
library(redistmetrics)
library(sf)
library(PL94171)
library(tinytiger)
library(tidyr)
library(dplyr)
library(alarmdata)
library(readr)
map_va <- alarm_50state_map('VA')

comp_polsby(plans = map_va_23$cd_2020, shp = map_va)
